version: 0.0.{build}
clone_folder: c:\gopath\src\github.com\mattn\sudo
environment:
  GOPATH: c:\gopath
install:
  - set PATH=c:\go\bin;%GOPATH%\bin;c:\tools\ruby215\bin;%PATH%;C:\MinGW\bin
  - echo %Path%
  - choco install -y ruby
  - rd c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.8.windows-amd64.zip
  - 7z x go1.8.windows-amd64.zip -oC:\ >nul
  - go version
  - go env
build_script:
  - go builx
test_script:
- go test -short ./...
#deploy:
#  release: $(appveyor_repo_tag_name)
#  provider: GitHub
#  auth_token:
#    secure: 
#  artifact: sudo
#  appveyor_repo_tag: true
#  force_update: true
#  on:
#    appveyor_repo_tag: true
#artifacts:
#  - path: sudo.exe
#    name: sudo
